import { departmentCategories, departmentTopics } from "@/lib/department-content";

export type Accent = "flare" | "info" | "rec" | "ok" | "amber";

export type Category = {
  id: string;
  name: string;
  abbr: string;
  blurb: string;
  accent: Accent;
  tool?: string;
  departments?: string[];
};

export type Topic = {
  slug: string;
  name: string;
  abbr?: string;
  category: string;
  definition: string;
  communicates: string;
  whenToUse: string;
  howToAchieve: string;
  equipment: string;
  commonMistake: string;
  compareWith?: string;
  accent: Accent;
  tool?: string;
  departments?: string[];
};

const baseCategories: Category[] = [
  { id: "exposure", name: "Exposure & Light", abbr: "EXP", blurb: "Triangle, frame rate, ISO & white balance", accent: "flare", tool: "/tools/exposure", departments: ["cinematography", "lighting-grip"] },
  { id: "shot-sizes", name: "Shot Sizes", abbr: "SIZ", blurb: "Where you crop the body changes meaning", accent: "info", tool: "/tools/shot-sizes", departments: ["cinematography", "directing", "script-continuity"] },
  { id: "camera-angles", name: "Camera Angles", abbr: "ANG", blurb: "Height & tilt shape power and feeling", accent: "info", tool: "/tools/angles", departments: ["cinematography", "directing"] },
  { id: "camera-movement", name: "Camera Movement", abbr: "MOV", blurb: "How the camera travels through space", accent: "flare", tool: "/tools/movement", departments: ["cinematography", "directing"] },
  { id: "composition", name: "Composition", abbr: "CMP", blurb: "Arrange the frame so the eye knows where to go", accent: "ok", tool: "/tools/composition", departments: ["cinematography", "directing", "production-design"] },
  { id: "lighting", name: "Lighting", abbr: "LGT", blurb: "Patterns, ratios and motivation", accent: "amber", tool: "/tools/lighting", departments: ["cinematography", "lighting-grip"] },
  { id: "audio", name: "Audio", abbr: "AUD", blurb: "Placement, gain and clean sound", accent: "info", tool: "/tools/audio", departments: ["sound", "editing-post"] },
  { id: "editing", name: "Editing Language", abbr: "EDT", blurb: "Cuts, continuity and pacing", accent: "flare", tool: "/learn", departments: ["editing-post", "directing", "script-continuity"] },
];

export const categories: Category[] = [...baseCategories, ...departmentCategories];

export const accentHex: Record<Accent, string> = {
  flare: "#a8362a",
  info: "#375c7d",
  rec: "#7d241d",
  ok: "#4c6b43",
  amber: "#a8781f",
};

const baseTopics: Topic[] = [
  // ---------------- EXPOSURE ----------------
  {
    slug: "aperture",
    name: "Aperture", abbr: "f-stop", category: "exposure", accent: "flare", tool: "/tools/exposure",
    definition: "The physical opening in the lens that controls how much light reaches the sensor, measured in f-stops.",
    communicates: "Lower f-numbers (f/1.4) read intimate, dreamy and isolated; higher numbers (f/11) read sharp, detailed and observational.",
    whenToUse: "Open up to separate a subject from a busy background. Stop down for landscapes, group shots and when you need everything sharp.",
    howToAchieve: "Turn the lens or rear dial to change the iris. Wider openings let in more light but shrink the depth of field.",
    equipment: "Any lens with a manual or electronic iris. Fast primes (f/1.4–f/1.8) give the strongest blur control.",
    commonMistake: "Assuming background blur is only about aperture — distance and focal length matter just as much.",
    compareWith: "Depth of field, ISO, shutter speed",
  },
  {
    slug: "shutter-speed",
    name: "Shutter Speed", abbr: "t", category: "exposure", accent: "flare", tool: "/tools/shutter",
    definition: "How long the sensor is exposed to light each frame, expressed as a fraction of a second (1/50s).",
    communicates: "Slower shutters smear motion for a smooth, filmic feel. Faster shutters freeze action for a crisp, sometimes harsh look.",
    whenToUse: "Hold near the 180° rule for natural motion. Go faster for sports and action; slower for stylised motion trails.",
    howToAchieve: "Set frame rate, then derive shutter from a shutter angle (180° = 1 ÷ (fps × 2)).",
    equipment: "Any camera. Variable ND lets you keep the 180° rule outdoors at wide apertures.",
    commonMistake: "Ignoring shutter in bright light and getting choppy, strobing motion at 1/1000s.",
    compareWith: "Frame rate, shutter angle, motion blur",
  },
  {
    slug: "iso",
    name: "ISO / Exposure Index", abbr: "ISO", category: "exposure", accent: "flare", tool: "/tools/exposure",
    definition: "A gain applied to the recorded signal to brighten the image after capture. Higher ISO = brighter but noisier.",
    communicates: "Clean low ISO reads premium and cinematic. Pushed ISO reads gritty, urgent or documentary.",
    whenToUse: "Keep at base ISO whenever there is enough light. Raise it when you cannot add light or open the lens further.",
    howToAchieve: "Raise ISO only after aperture and shutter are set for the look you want. Know your camera's base and second native ISO.",
    equipment: "All cameras. Dual-native sensors keep noise low across two plateaus.",
    commonMistake: "Treating ISO as a free brightness dial and pushing into unusable noise.",
    compareWith: "Base ISO, dual-native ISO, exposure index",
  },
  {
    slug: "nd-filters",
    name: "ND Filters", abbr: "ND", category: "exposure", accent: "flare", tool: "/tools/shutter",
    definition: "Neutral-density glass that darkens the whole frame evenly without changing colour, so you can keep a wide aperture and the 180° shutter in bright light.",
    communicates: "Lets you shoot creamy shallow focus outdoors — the daylight shot that still feels cinematic.",
    whenToUse: "Any time bright light forces you to stop down or speed up the shutter against the look you want.",
    howToAchieve: "Screw-in fixed NDs (cleaner) or a variable ND (fast but watch for the cross / colour shift).",
    equipment: "Screw-in NDs, matte-box NDs, or a quality variable ND.",
    commonMistake: "Cheap variable NDs showing an X pattern or colour cast at extremes.",
    compareWith: "Polariser, aperture, shutter angle",
  },
  {
    slug: "white-balance",
    name: "White Balance", abbr: "WB / K", category: "exposure", accent: "flare", tool: "/tools/white-balance",
    definition: "Telling the camera what neutral white looks like so colours render accurately, set in Kelvin.",
    communicates: "Warm Kelvin (3200K) feels cosy, nostalgic, candlelit. Cool Kelvin (6500K+) feels clinical, cold, modern.",
    whenToUse: "Match the dominant light source for accuracy, or shift intentionally for mood. Lock it for continuity across shots.",
    howToAchieve: "Pick a Kelvin value, use a preset, or take a custom reading off a white card. Avoid auto WB for narrative work.",
    equipment: "Any camera plus a grey or white card for custom readings.",
    commonMistake: "Leaving auto WB on during a shot and watching colour drift as the subject moves.",
    compareWith: "Tint, colour temperature, mixed light",
  },
  {
    slug: "exposure-triangle",
    name: "Exposure Triangle", abbr: "EV", category: "exposure", accent: "flare", tool: "/tools/exposure",
    definition: "Aperture, shutter and ISO working together. Change one and you trade brightness against a creative side-effect.",
    communicates: "The mental model that stops you fighting your camera and lets you choose a look deliberately.",
    whenToUse: "Any time you expose manually. Decide the look first, then let one setting absorb the brightness.",
    howToAchieve: "Lock the two settings that define your look (say aperture + shutter) and let ISO absorb the light.",
    equipment: "Any camera body and lens.",
    commonMistake: "Chasing a 'correct' exposure instead of the exposure that serves the story.",
    compareWith: "Aperture, shutter speed, ISO",
  },

  // ---------------- SHOT SIZES ----------------
  {
    slug: "extreme-wide-shot",
    name: "Extreme Wide Shot", abbr: "EWS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "A vast framing where the subject is a tiny mark inside a large landscape or location.",
    communicates: "Scale, isolation, awe. The human is dwarfed by the world.",
    whenToUse: "To open a film or sequence, establish geography, or make a character feel alone.",
    howToAchieve: "Wide lens, far distance, lots of negative space around the figure.",
    equipment: "Ultrawide lens (14–24mm). Drone, crane or a high vantage point.",
    commonMistake: "No clear subject — the eye doesn't know where to land.",
    compareWith: "Establishing shot, wide shot",
  },
  {
    slug: "wide-shot",
    name: "Wide Shot", abbr: "WS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "The full body and a good amount of the surrounding space are visible.",
    communicates: "Context and action. We see where the character is and what they are doing.",
    whenToUse: "To show movement, blocking and environment without losing the character.",
    howToAchieve: "Wide lens at a comfortable distance, figure head-to-toe with breathing room.",
    equipment: "Wide-to-normal lens (24–35mm).",
    commonMistake: "Too much headroom and dead space above the subject.",
    compareWith: "Full shot, establishing shot",
  },
  {
    slug: "full-shot",
    name: "Full Shot", abbr: "FS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "The entire body fills the frame, cropped just above the head and below the feet.",
    communicates: "Posture, costume and physical performance. The body tells the story.",
    whenToUse: "For dance, fights, walking-and-talking and any whole-body action.",
    howToAchieve: "Frame the figure fully; keep the feet included so action has a floor.",
    equipment: "Normal lens (35–50mm).",
    commonMistake: "Cutting off the feet or knees — it feels like an accident.",
    compareWith: "Wide shot, medium wide shot",
  },
  {
    slug: "medium-wide-shot",
    name: "Medium Wide Shot", abbr: "MWS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "Crops the body from roughly the knees up.",
    communicates: "A friendly, social distance — like standing across a room from someone.",
    whenToUse: "Group conversations and the in-between beat between full and medium.",
    howToAchieve: "Frame from mid-thigh or knee up, with comfortable headroom.",
    equipment: "Normal lens (35–50mm).",
    commonMistake: "Cutting at a joint (knee) which reads awkwardly.",
    compareWith: "Cowboy shot, full shot",
  },
  {
    slug: "cowboy-shot",
    name: "Cowboy Shot", abbr: "CS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "Crops from mid-thigh up — historically so a holstered gun stays in frame.",
    communicates: "Tension and readiness. A stylised, slightly theatrical distance.",
    whenToUse: "Standoffs, confrontations, or whenever you want hands and hips in frame.",
    howToAchieve: "Frame so the subject's upper thighs and hips are visible.",
    equipment: "Normal-to-short-tele lens (35–50mm).",
    commonMistake: "Cropping too high and losing the intended 'gun-slinger' weight.",
    compareWith: "Medium wide shot, medium shot",
  },
  {
    slug: "medium-shot",
    name: "Medium Shot", abbr: "MS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "Crops from the waist up — the workhorse of dialogue.",
    communicates: "Conversational intimacy while still seeing gestures and body language.",
    whenToUse: "The default for interviews and dialogue; the most natural 'talking' distance.",
    howToAchieve: "Frame from the waist or lower chest up with slight headroom.",
    equipment: "Normal-to-tele lens (35–85mm).",
    commonMistake: "Cutting at the wrist so hands look amputated mid-gesture.",
    compareWith: "Medium close-up, medium wide shot",
  },
  {
    slug: "medium-close-up",
    name: "Medium Close-Up", abbr: "MCU", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "Crops from the chest or shoulders up.",
    communicates: "Warmth and focus — close enough to read emotion, far enough to feel social.",
    whenToUse: "The favoured interview and news framing; great for empathetic dialogue.",
    howToAchieve: "Frame from the upper chest up with the head near the top third.",
    equipment: "Portrait tele lens (50–85mm).",
    commonMistake: "Too much headroom, turning an MCU into a loose medium.",
    compareWith: "Medium shot, close-up",
  },
  {
    slug: "close-up",
    name: "Close-Up", abbr: "CU", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "The face fills the frame, filling the screen with emotion.",
    communicates: "Interiority. We feel what the character feels, not what they do.",
    whenToUse: "For reaction, realisation and emotional peaks. The key storytelling beat.",
    howToAchieve: "Frame the face from forehead to chin/upper chest, eyes on the upper third.",
    equipment: "Tele lens (85–135mm) to avoid distortion.",
    commonMistake: "Cutting the chin or leaving the face dead-centre with no looking room.",
    compareWith: "Medium close-up, extreme close-up",
  },
  {
    slug: "extreme-close-up",
    name: "Extreme Close-Up", abbr: "ECU", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "A single detail fills the frame — an eye, a hand, an object.",
    communicates: "Intensity, obsession or revelation. The smallest thing becomes everything.",
    whenToUse: "Sparingly, for maximum emphasis or to point at a critical detail.",
    howToAchieve: "Get physically or optically close; crop tightly on one feature.",
    equipment: "Macro or long tele lens; diopters for close focusing.",
    commonMistake: "Overusing it until it loses its punch.",
    compareWith: "Close-up, insert shot",
  },
  {
    slug: "insert-shot",
    name: "Insert Shot", abbr: "INS", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "A close framing of an object, note or action the audience must register.",
    communicates: "This detail matters. It plants information or pays off a setup.",
    whenToUse: "To clarify story, show a clue, or smooth over an edit in dialogue coverage.",
    howToAchieve: "Shoot a tight, well-lit plate of the detail, usually on a separate setup.",
    equipment: "Macro or short tele lens; small light or reflector.",
    commonMistake: "Shooting it from a different eyeline or angle that breaks continuity.",
    compareWith: "Cutaway, extreme close-up",
  },
  {
    slug: "establishing-shot",
    name: "Establishing Shot", abbr: "EST", category: "shot-sizes", accent: "info", tool: "/tools/shot-sizes",
    definition: "A wide framing that tells the audience where and when the scene takes place.",
    communicates: "Orientation. A promise of the world we are about to enter.",
    whenToUse: "At the head of a scene, sequence or new location.",
    howToAchieve: "Shoot wide and steady, often from elevation; let it run a few beats.",
    equipment: "Ultrawide lens, drone, crane or high position.",
    commonMistake: "Dwelling too long or re-establishing unnecessarily inside a scene.",
    compareWith: "Extreme wide shot, wide shot",
  },

  // ---------------- CAMERA ANGLES ----------------
  {
    slug: "eye-level",
    name: "Eye Level", abbr: "0°", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The lens sits level with the subject's eyes — a neutral, equal perspective.",
    communicates: "Objectivity and empathy. The viewer is a peer, not a judge.",
    whenToUse: "As the default for most drama and interviews; it disappears and lets the story through.",
    howToAchieve: "Set the tripod so the lens height matches the subject's eye line.",
    equipment: "Any camera on a height-adjustable support.",
    commonMistake: "Shooting down at children or seated subjects 'from above' by default.",
    compareWith: "High angle, low angle",
  },
  {
    slug: "high-angle",
    name: "High Angle", abbr: "HIGH", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera looks down on the subject from above eye level.",
    communicates: "Vulnerability, smallness or loss of power.",
    whenToUse: "When a character is overwhelmed, defeated or being observed.",
    howToAchieve: "Raise the camera and tilt down toward the subject.",
    equipment: "Raised tripod, jib, drone or a high vantage point.",
    commonMistake: "Overdoing it until the angle becomes the only thing the viewer notices.",
    compareWith: "Low angle, eye level",
  },
  {
    slug: "low-angle",
    name: "Low Angle", abbr: "LOW", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera looks up at the subject from below eye level.",
    communicates: "Power, dominance, heroism or menace.",
    whenToUse: "To make a character imposing, heroic or threatening.",
    howToAchieve: "Drop the camera low and tilt up at the subject.",
    equipment: "Low-mode tripod, ground pod or a camera placed on the floor.",
    commonMistake: "Accidentally emphasising nostrils and chins on unflattering close-ups.",
    compareWith: "High angle, ground level",
  },
  {
    slug: "ground-level",
    name: "Ground Level", abbr: "GND", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The lens is at floor level, looking out across the ground.",
    communicates: "A child's or animal's point of view; motion and scale near the floor.",
    whenToUse: "For feet, vehicles, low action and dramatic foregrounds.",
    howToAchieve: "Place the camera on or just above the ground with a wide lens.",
    equipment: "Ground pod, beanbag or low-mode rig.",
    commonMistake: "Forgetting the foreground will be huge and possibly distracting.",
    compareWith: "Low angle, knee level",
  },
  {
    slug: "birds-eye",
    name: "Bird's-Eye / Overhead", abbr: "TOP", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera looks straight down from directly above the subject.",
    communicates: "Omniscience, geometry, surveillance or pattern.",
    whenToUse: "For table tops, choreography, maps and stylised transitions.",
    howToAchieve: "Mount the camera overhead on a boom, C-stand or drone pointing down.",
    equipment: "Jib, overhead rig, drone or mounted top-down stand.",
    commonMistake: "Weak lighting from below creating ugly flat or raking shadows.",
    compareWith: "High angle, ground level",
  },
  {
    slug: "dutch-angle",
    name: "Dutch Angle", abbr: "DUTCH", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera is rolled so the horizon is off-level.",
    communicates: "Unease, disorientation, tension or that something is wrong.",
    whenToUse: "For psychological disturbance, thriller beats and stylised energy.",
    howToAchieve: "Roll the camera off-axis — a few degrees for unease, more for chaos.",
    equipment: "Any camera; a levelling head that lets you deliberately tilt.",
    commonMistake: "Using it randomly so it loses meaning and just feels like a mistake.",
    compareWith: "Eye level, roll",
  },
  {
    slug: "over-the-shoulder",
    name: "Over-the-Shoulder", abbr: "OTS", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera shoots past one character's shoulder toward another.",
    communicates: "Connection and conflict between two people in a conversation.",
    whenToUse: "For dialogue coverage — the glue of shot/reverse-shot editing.",
    howToAchieve: "Place the camera behind one actor, framing the other with a sliver of foreground shoulder.",
    equipment: "Tele lens (50–85mm) to compress the two figures.",
    commonMistake: "Foreground shoulder covering too much of the speaker's face.",
    compareWith: "Two-shot, POV",
  },
  {
    slug: "point-of-view",
    name: "Point of View", abbr: "POV", category: "camera-angles", accent: "info", tool: "/tools/angles",
    definition: "The camera shows what a character sees from their eyes.",
    communicates: "Immersion and identification — the viewer becomes the character.",
    whenToUse: "For reveals, horror, first-person moments and subjective emotion.",
    howToAchieve: "Match the lens height and movement to the character's head; keep eyelines consistent.",
    equipment: "Body rig, Steadicam or handheld at eye height.",
    commonMistake: "Inconsistent height and direction that breaks the POV illusion.",
    compareWith: "Over-the-shoulder, eyeline match",
  },

  // ---------------- CAMERA MOVEMENT ----------------
  {
    slug: "pan",
    name: "Pan", abbr: "PAN", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The camera rotates horizontally left or right while staying in one spot.",
    communicates: "Surveying a space, following action, or revealing something off-screen.",
    whenToUse: "To follow a moving subject or sweep across a landscape.",
    howToAchieve: "Lock the tripod legs; rotate only on the pan axis from a fluid head.",
    equipment: "Fluid head on a tripod. Glide the move, do not jerk it.",
    commonMistake: "Confusing a pan with a truck — a pan rotates, it does not travel sideways.",
    compareWith: "Tilt, truck, whip pan",
  },
  {
    slug: "tilt",
    name: "Tilt", abbr: "TILT", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The camera rotates vertically up or down while staying in one spot.",
    communicates: "Revealing height — from feet to face, or ground to skyline.",
    whenToUse: "To reveal a tall subject or emphasise vertical scale.",
    howToAchieve: "Lock the legs; tilt only on the vertical axis of a fluid head.",
    equipment: "Fluid head on a tripod.",
    commonMistake: "Letting the pan loosen so the head drifts sideways mid-tilt.",
    compareWith: "Pan, pedestal",
  },
  {
    slug: "dolly-in",
    name: "Dolly In / Out", abbr: "DOLLY", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The whole camera physically travels toward (in) or away from (out) the subject.",
    communicates: "In = growing intimacy, revelation or focus. Out = distance, scale or ending.",
    whenToUse: "To pull the viewer emotionally closer during a key beat, or to reveal context by pulling back.",
    howToAchieve: "Move the camera along a track or smooth surface on a wheeled dolly.",
    equipment: "Track-and-dolly, slider, gimbal or steadicam with a pusher.",
    commonMistake: "Confusing it with a zoom — a dolly moves the camera and changes perspective; a zoom does not.",
    compareWith: "Zoom, push-in, truck",
  },
  {
    slug: "truck",
    name: "Truck Left / Right", abbr: "TRK", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The whole camera moves laterally left or right, keeping its facing direction.",
    communicates: "Tracking a subject through space and adding parallax depth.",
    whenToUse: "To walk alongside a character or layer foreground and background.",
    howToAchieve: "Move the dolly perpendicular to the lens axis on track or a smooth floor.",
    equipment: "Dolly on track, slider, gimbal or a doorway dolly.",
    commonMistake: "Calling it a pan — a pan rotates in place; a truck translates sideways.",
    compareWith: "Pan, tracking, arc",
  },
  {
    slug: "pedestal",
    name: "Pedestal Up / Down", abbr: "PED", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The whole camera rises or falls vertically while keeping its angle.",
    communicates: "A clean reveal of height without the tilt distortion — like an elevator for the lens.",
    whenToUse: "To follow a standing or sitting subject, or reveal a tall subject without tilting.",
    howToAchieve: "Crank or motor the pedestal column up or down while the head stays level.",
    equipment: "Pedestal (studio), jib, or a motorised lift.",
    commonMistake: "Confusing it with a tilt — a tilt rotates; a pedestal keeps the angle and moves.",
    compareWith: "Tilt, boom",
  },
  {
    slug: "boom",
    name: "Boom / Jib", abbr: "JIB", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "A long arm swings the camera through a high arc, combining vertical and horizontal travel.",
    communicates: "Sweeping grandeur, dramatic reveals and god-like perspective.",
    whenToUse: "For big emotional or spatial reveals and to fly over obstacles.",
    howToAchieve: "Pivot a counter-weighted jib or crane, controlling pan/tilt remotely at the tip.",
    equipment: "Jib, crane or technocrane with a remote head.",
    commonMistake: "Relying on motion to hide a poorly composed frame.",
    compareWith: "Pedestal, tilt, arc",
  },
  {
    slug: "arc",
    name: "Arc / Orbit", abbr: "ARC", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The camera curves around the subject, keeping roughly the same distance.",
    communicates: "Dimension and dynamism — the world turns around a fixed subject.",
    whenToUse: "To wrap a frozen or slow moment in energy and three-dimensionality.",
    howToAchieve: "Walk or roll the camera along a radius around the subject.",
    equipment: "Gimbal, steadicam, dolly on a curved track or a handheld arc step.",
    commonMistake: "Drifting closer or farther so distance and focus shift unpredictably.",
    compareWith: "Orbit, truck",
  },
  {
    slug: "zoom",
    name: "Zoom In / Out", abbr: "ZOOM", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The focal length changes from a fixed position, magnifying the subject without moving the camera.",
    communicates: "Sudden attention or dread (snap zoom) or stylised energy (slow zoom).",
    whenToUse: "Deliberately for effect; otherwise many filmmakers prefer moving the camera.",
    howToAchieve: "Turn the zoom ring or push a servo zoom rocker on a parfocal lens.",
    equipment: "Zoom lens (parfocal preferred so focus holds through the range).",
    commonMistake: "Confusing it with a dolly — zoom magnifies without changing perspective or depth.",
    compareWith: "Dolly in, dolly zoom",
  },
  {
    slug: "dolly-zoom",
    name: "Dolly Zoom (Vertigo)", abbr: "D-ZOOM", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "Dolly in while zooming out (or vice-versa) to keep the subject the same size while the background warps.",
    communicates: "A sickening realisation — the world shifts while the character is frozen.",
    whenToUse: "For a moment of shock, dread or sudden understanding.",
    howToAchieve: "Coordinate the dolly speed and zoom ratio so the subject size stays constant.",
    equipment: "Dolly/track plus a zoom lens, or a motorised lens control.",
    commonMistake: "Letting the subject grow or shrink so the effect reads as an ordinary push.",
    compareWith: "Zoom, dolly in",
  },
  {
    slug: "tracking",
    name: "Tracking Shot", abbr: "TRK", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The camera follows a subject through a space, often over a long, continuous path.",
    communicates: "Immersion and momentum — the viewer is carried through the world.",
    whenToUse: "For continuous action, oners and to establish a location while moving.",
    howToAchieve: "Match the subject's pace using a gimbal, steadicam or dolly on track.",
    equipment: "Gimbal, steadicam, dolly, or a stabilised handheld rig.",
    commonMistake: "Uneven pace that pulls ahead of or lags behind the subject.",
    compareWith: "Truck, dolly in",
  },
  {
    slug: "whip-pan",
    name: "Whip Pan", abbr: "WHIP", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "A fast, blurred pan used as a hard transition or energy hit.",
    communicates: "Speed, chaos or a smash-cut in-camera.",
    whenToUse: "To hide a cut, match two whip pans together, or inject sudden energy.",
    howToAchieve: "Snap the fluid head hard and fast, then settle. Match speed for edits.",
    equipment: "Fluid head or handheld.",
    commonMistake: "Speed so uncontrolled that the start and end frames are unusable.",
    compareWith: "Pan, smash cut",
  },
  {
    slug: "handheld",
    name: "Handheld", abbr: "HH", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "The camera is held by the operator, introducing organic micro-movement.",
    communicates: "Documentary immediacy, tension or chaos.",
    whenToUse: "For realism, urgency and the feeling of 'being there'.",
    howToAchieve: "Hold close to the body, tuck elbows, and walk with bent knees to smooth steps.",
    equipment: "Light camera, rig with grips, or a stabilising monitor.",
    commonMistake: "Mistaking shake for energy — too much wobble just reads sloppy.",
    compareWith: "Gimbal, static",
  },
  {
    slug: "gimbal",
    name: "Gimbal Move", abbr: "GMB", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "A motorised stabiliser holds the camera level, so operator movement reads as smooth glide.",
    communicates: "Fluid, floating, almost weightless motion.",
    whenToUse: "For tracking, arcs and dynamic moves where a tripod dolly won't fit.",
    howToAchieve: "Balance the camera, set follow modes, and walk with a 'ninja' heel-toe step.",
    equipment: "3-axis gimbal, monitor and battery system.",
    commonMistake: "Over-stabilising every shot until the film loses tactile energy.",
    compareWith: "Handheld, tracking",
  },
  {
    slug: "static",
    name: "Static / Locked-Off", abbr: "STAT", category: "camera-movement", accent: "flare", tool: "/tools/movement",
    definition: "A deliberately still, locked frame with no movement.",
    communicates: "Control, stillness and observation. The action moves; the camera does not.",
    whenToUse: "For graphic compositions, deadpan comedy and letting blocking do the work.",
    howToAchieve: "Lock a sturdy tripod; turn off image stabilisation if it introduces drift.",
    equipment: "Heavy tripod, sandbags, locked head.",
    commonMistake: "An unlocked head that creeps and ruins a precise composition.",
    compareWith: "Handheld, push-in",
  },

  // ---------------- COMPOSITION ----------------
  {
    slug: "rule-of-thirds",
    name: "Rule of Thirds", abbr: "1/3", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Divide the frame into thirds and place the subject or horizon on those lines or intersections.",
    communicates: "Balance and natural flow. The eye prefers off-centre energy to a dead-centre subject.",
    whenToUse: "As a reliable default for almost any subject; break it only with intent.",
    howToAchieve: "Overlay a thirds grid and place key elements on a line or intersection.",
    equipment: "In-camera grid overlay or your eye.",
    commonMistake: "Treating it as a rule rather than a starting point.",
    compareWith: "Centre framing, golden ratio",
  },
  {
    slug: "centre-framing",
    name: "Centre Framing", abbr: "CTR", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Placing the subject dead-centre for symmetry and direct address.",
    communicates: "Formality, confrontation or intimacy. The subject confronts the viewer.",
    whenToUse: "For symmetry, POV, Wes Anderson-style graphic balance and direct-to-camera.",
    howToAchieve: "Centre the subject on the vertical axis; pair it with a symmetrical background.",
    equipment: "In-camera grid; a level head.",
    commonMistake: "Centre-framing an asymmetric scene so it just looks off-balance.",
    compareWith: "Rule of thirds, symmetry",
  },
  {
    slug: "leading-lines",
    name: "Leading Lines", abbr: "→", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Using roads, rails, walls or light to point the eye toward the subject.",
    communicates: "Direction and destination — the viewer's eye is guided, not left to wander.",
    whenToUse: "Whenever the environment offers a line that can deliver the eye to your subject.",
    howToAchieve: "Position the camera so environmental lines converge on the subject.",
    equipment: "Any lens; wide lenses exaggerate converging lines.",
    commonMistake: "Lines that point nowhere or lead the eye out of the frame.",
    compareWith: "Depth, negative space",
  },
  {
    slug: "negative-space",
    name: "Negative Space", abbr: "NEG", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Leaving large empty area around a small subject.",
    communicates: "Isolation, scale, calm or loneliness.",
    whenToUse: "To suggest emptiness, breathing room, or anticipation of something entering.",
    howToAchieve: "Push the subject to one edge and let the rest of the frame fall away.",
    equipment: "Wide lens; a clean, uncluttered background.",
    commonMistake: "So much emptiness the subject gets lost and the eye can't settle.",
    compareWith: "Balance, rule of thirds",
  },
  {
    slug: "headroom",
    name: "Headroom", abbr: "HR", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "The space between the top of the subject's head and the top of the frame.",
    communicates: "Too much reads distant and wasteful; too little feels cramped and claustrophobic.",
    whenToUse: "Keep it tight but present — a sliver above the head for most portraits.",
    howToAchieve: "Tilt or reframe so there is a small, consistent gap above the head.",
    equipment: "In-camera grid; a fluid head for micro-adjustments.",
    commonMistake: "Too much headroom leaving dead space above the subject.",
    compareWith: "Looking room, nose room",
  },
  {
    slug: "looking-room",
    name: "Looking / Lead Room", abbr: "LR", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "The space in front of a subject's face or gaze direction.",
    communicates: "Gives the subject somewhere to look or move into — space to breathe.",
    whenToUse: "Always leave more room in the direction the subject faces or moves.",
    howToAchieve: "Frame the subject toward the back third so their gaze leads into open space.",
    equipment: "Any setup; an awareness of eyeline direction.",
    commonMistake: "Cramming the subject against the edge they are looking toward.",
    compareWith: "Headroom, rule of thirds",
  },
  {
    slug: "symmetry",
    name: "Symmetry", abbr: "SYM", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Mirroring elements left/right or top/bottom for graphic balance.",
    communicates: "Order, power, beauty or unease when deliberately broken.",
    whenToUse: "For formal compositions, grand architecture and stylised storytelling.",
    howToAchieve: "Centre the camera on the axis of symmetry and level the horizon.",
    equipment: "Level tripod; a wide, distortion-free lens.",
    commonMistake: "A slightly off-centre axis that ruins the mirror without intent.",
    compareWith: "Centre framing, balance",
  },
  {
    slug: "depth",
    name: "Foreground / Depth", abbr: "DPT", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Layering foreground, midground and background to build three dimensions.",
    communicates: "Dimension and immersion — the frame feels like a space, not a flat image.",
    whenToUse: "Whenever you want the viewer to feel inside the environment.",
    howToAchieve: "Shoot through foreground objects; separate planes with light and focus.",
    equipment: "Wider lens, deeper staging, selective focus.",
    commonMistake: "A flat, single-layer frame with no foreground to anchor depth.",
    compareWith: "Leading lines, foreground layering",
  },
  {
    slug: "frame-within-a-frame",
    name: "Frame Within a Frame", abbr: "FWF", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Using doorways, windows or arches to frame the subject inside the frame.",
    communicates: "Voyeurism, confinement or focus — it points precisely at the subject.",
    whenToUse: "To isolate a subject, suggest they are watched, or add graphic interest.",
    howToAchieve: "Position a doorway, window or arch as an inner border around the subject.",
    equipment: "Any lens; careful camera placement.",
    commonMistake: "A 'frame' that competes with rather than supports the subject.",
    compareWith: "Foreground layering, negative space",
  },
  {
    slug: "balance",
    name: "Balance", abbr: "BAL", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Distributing visual weight across the frame so it feels stable or intentionally off.",
    communicates: "Balance feels calm and resolved; imbalance feels tense and dynamic.",
    whenToUse: "Balance for serenity; tip the balance to add energy or unease.",
    howToAchieve: "Counter a heavy subject with negative space, colour or a secondary element.",
    equipment: "Any setup; an eye for visual weight.",
    commonMistake: "Two equally heavy objects fighting for attention with no hierarchy.",
    compareWith: "Rule of thirds, symmetry",
  },
  {
    slug: "diagonal-composition",
    name: "Diagonal Composition", abbr: "DIAG", category: "composition", accent: "ok", tool: "/tools/composition",
    definition: "Composing along a diagonal axis to inject movement and energy.",
    communicates: "Dynamism and tension — diagonals feel active where horizontals feel calm.",
    whenToUse: "For action, drama and any frame that needs forward energy.",
    howToAchieve: "Tilt the camera, use diagonal lines, or stage action across the frame.",
    equipment: "Any lens; Dutch tilts or diagonal staging.",
    commonMistake: "A diagonal with no payoff that just reads like a crooked horizon.",
    compareWith: "Leading lines, balance",
  },

  // ---------------- LIGHTING ----------------
  {
    slug: "three-point-lighting",
    name: "Three-Point Lighting", abbr: "3PT", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A key, fill and back light working together to shape and separate the subject.",
    communicates: "A polished, flattering, professional look — the baseline for interviews and portraits.",
    whenToUse: "As a reliable foundation you can then modify for mood.",
    howToAchieve: "Place a key at 45° front-side, a soft fill to lift shadows, and a back light for separation.",
    equipment: "Three lights (or two plus a reflector), plus stands and modifiers.",
    commonMistake: "Flat fill that kills the shaping the key just created.",
    compareWith: "Rembrandt, loop, butterfly",
  },
  {
    slug: "rembrandt-lighting",
    name: "Rembrandt Lighting", abbr: "REMB", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A side key placed to create a small triangle of light on the shadowed cheek.",
    communicates: "Painterly drama and depth — moody but flattering.",
    whenToUse: "For portraits that need character and a sense of gravity.",
    howToAchieve: "Angle the key about 45° to the side and slightly above until the nose shadow forms a triangle.",
    equipment: "One focused key; optional fill to soften.",
    commonMistake: "Lighting so steep the triangle never forms or the eyes fall into shadow.",
    compareWith: "Loop, split lighting",
  },
  {
    slug: "butterfly-lighting",
    name: "Butterfly (Paramount)", abbr: "BFLY", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A key placed directly above the lens axis, casting a symmetrical butterfly shadow under the nose.",
    communicates: "Glamour, symmetry and a classic beauty-portrait look.",
    whenToUse: "For beauty, fashion and flattering headshots.",
    howToAchieve: "Raise the key directly above the camera, aimed down at the face; add a reflector below.",
    equipment: "Boom-mounted key; an under-fill reflector.",
    commonMistake: "Harsh downward shadow that ages the face; soften with diffusion.",
    compareWith: "Loop, Rembrandt",
  },
  {
    slug: "loop-lighting",
    name: "Loop Lighting", abbr: "LOOP", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A key placed at a moderate front-side angle so the nose casts a small loop shadow toward the cheek.",
    communicates: "Flattering, safe and natural — the most common portrait pattern.",
    whenToUse: "As the default flattering setup for interviews and headshots.",
    howToAchieve: "Position the key 30–45° to the side and slightly above eye level.",
    equipment: "One soft key; optional fill.",
    commonMistake: "Letting the loop grow into a harsh nose shadow by going too steep or too side.",
    compareWith: "Rembrandt, butterfly",
  },
  {
    slug: "split-lighting",
    name: "Split Lighting", abbr: "SPLT", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A side key lights exactly half the face, leaving the other half in shadow.",
    communicates: "Conflict, duality or menace — two sides of a character.",
    whenToUse: "For antagonists, internal conflict and high drama.",
    howToAchieve: "Place the key exactly 90° to the side at face height.",
    equipment: "One hard or soft side key; negative fill to deepen the shadow side.",
    commonMistake: "Accidental fill bouncing in and washing out the split.",
    compareWith: "Rembrandt, side light",
  },
  {
    slug: "hard-vs-soft",
    name: "Hard vs Soft Light", abbr: "H/S", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "Hard light has a small source and sharp shadows; soft light has a large source and gentle gradients.",
    communicates: "Hard reads edgy, dramatic and masculine; soft reads flattering, gentle and modern.",
    whenToUse: "Hard for texture and drama; soft for beauty and interviews.",
    howToAchieve: "Soften by enlarging the source (diffusion, bounce) or moving it closer; harden by removing diffusion.",
    equipment: "Diffusion fabric, softboxes, umbrellas, or bare reflectors.",
    commonMistake: "Confusing brightness with hardness — a bright light can still be soft if the source is large.",
    compareWith: "Three-point, inverse square",
  },
  {
    slug: "backlight",
    name: "Back / Rim Light", abbr: "RIM", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A light placed behind the subject to outline the edge and separate it from the background.",
    communicates: "Separation, sheen and dimension — the subject pops off the background.",
    whenToUse: "Whenever the subject blends into a dark or similar-toned background.",
    howToAchieve: "Place a light behind and slightly above, raking the shoulder and hair.",
    equipment: "A focused spot or bare lamp behind the subject, flagged off the lens.",
    commonMistake: "Spilling back light into the lens and causing flare or haze.",
    compareWith: "Three-point, front light",
  },
  {
    slug: "low-key",
    name: "Low-Key Lighting", abbr: "LK", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A predominantly dark image with selective light and deep shadows.",
    communicates: "Mystery, noir, intimacy or threat.",
    whenToUse: "For drama, thrillers and moody, character-driven scenes.",
    howToAchieve: "Use one focused key, kill ambient fill, and add negative fill to deepen shadows.",
    equipment: "Controlled key, flags, black wrap and negative-fill panels.",
    commonMistake: "Underexposing so far the shadows turn to mush and lose detail.",
    compareWith: "High-key, split",
  },
  {
    slug: "high-key",
    name: "High-Key Lighting", abbr: "HK", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "A bright, evenly lit image with soft shadows and low contrast.",
    communicates: "Optimism, cleanliness, comedy and commercial polish.",
    whenToUse: "For comedy, commercials, sit-coms and corporate work.",
    howToAchieve: "Flood the scene with soft, even light and lift the shadows with fill.",
    equipment: "Multiple soft sources, large bounces and high ambient fill.",
    commonMistake: "Going so flat the image loses shape and dimension.",
    compareWith: "Low-key, three-point",
  },
  {
    slug: "negative-fill",
    name: "Negative Fill", abbr: "-F", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "Using black flags or cloth to subtract light and deepen shadows on the fill side.",
    communicates: "Contrast and shape — it makes a flat soft-lit face feel sculpted.",
    whenToUse: "Whenever soft ambient light is flattening your subject.",
    howToAchieve: "Place black floppy or duvetyne on the opposite side to the key to absorb bounce.",
    equipment: "Black flags, floppy, duvetyne or a black card.",
    commonMistake: "Forgetting that white walls bounce light even when you think the room is dark.",
    compareWith: "Fill ratio, low-key",
  },
  {
    slug: "inverse-square",
    name: "Inverse-Square Law", abbr: "ISL", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "Light falls off fast — double the distance and you get a quarter of the light.",
    communicates: "Why moving a light a little changes brightness a lot, and why backgrounds go dark close to a subject.",
    whenToUse: "To control falloff, separate subject from background, or balance two sources.",
    howToAchieve: "Bring a light close for fast falloff and dark backgrounds; move it far for even coverage.",
    equipment: "Any light and a tape measure.",
    commonMistake: "Putting lights too far, then fighting to brighten them with ISO.",
    compareWith: "Fill ratio, hard vs soft",
  },
  {
    slug: "motivated-lighting",
    name: "Motivated Lighting", abbr: "MOT", category: "lighting", accent: "amber", tool: "/tools/lighting",
    definition: "Lighting that imitates a believable in-world source — a window, a lamp, a TV.",
    communicates: "Realism — the light feels like it belongs to the scene, not the crew.",
    whenToUse: "For naturalistic narrative and anytime you want the lighting to feel invisible.",
    howToAchieve: "Identify the practical source, then replicate its direction, colour and softness.",
    equipment: "Practicals plus off-camera lights matched in colour and direction.",
    commonMistake: "Lighting from a direction that has no visible source, breaking the illusion.",
    compareWith: "Practical light, three-point",
  },

  // ---------------- AUDIO ----------------
  {
    slug: "lavalier-placement",
    name: "Lavalier Placement", abbr: "LAV", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "Clipping a small mic to the chest, hidden in clothing, 15–25cm from the mouth.",
    communicates: "Invisible, consistent dialogue capture — the standard for interviews.",
    whenToUse: "For talking-head video, documentary and any fixed presenter.",
    howToAchieve: "Place the capsule mid-chest, route and tape the cable to stop rustle, leave a strain relief loop.",
    equipment: "Wired or wireless lav, moleskin/medical tape, a tiny windscreen.",
    commonMistake: "Clothing rustle and cable noise from a tight, rub-prone mount.",
    compareWith: "Boom, shotgun",
  },
  {
    slug: "boom-placement",
    name: "Boom Placement", abbr: "BOOM", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "A directional mic on a pole, hovered just out of frame above the subject.",
    communicates: "Natural, high-quality sound that captures the voice in its real space.",
    whenToUse: "For narrative dialogue where lavs are visible or unwanted.",
    howToAchieve: "Get the capsule as close as possible without entering frame, aimed at the mouth from above.",
    equipment: "Shotgun or hypercardioid mic, boom pole, shock mount, suspension.",
    commonMistake: "Booming from too far, so the room swallows the voice.",
    compareWith: "Lavalier, shotgun",
  },
  {
    slug: "gain-staging",
    name: "Gain Staging", abbr: "GAIN", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "Setting each link in the chain — mic, transmitter, receiver, camera — to an optimum level.",
    communicates: "Clean, noise-free audio with headroom instead of hiss or distortion.",
    whenToUse: "Always — at the start of every setup, before you press record.",
    howToAchieve: "Set the strongest source first, peak around -12 to -6 dBFS, leave headroom for loud moments.",
    equipment: "Any recorder or wireless system with meters.",
    commonMistake: "Setting camera input too hot and clipping, or too low and raising hiss in post.",
    compareWith: "Audio meter, safety track",
  },
  {
    slug: "safety-track",
    name: "Safety Track (-10 dB)", abbr: "SAF", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "A second channel recorded 10 dB quieter to catch peaks that clip the main channel.",
    communicates: "Insurance against clipping on a shout or unexpected loud moment.",
    whenToUse: "Whenever levels are unpredictable — interviews, live events, energetic talent.",
    howToAchieve: "Record two channels at different gains, or use a recorder with a built-in safety track.",
    equipment: "Dual-channel recorder or wireless with safety-track mode.",
    commonMistake: "Forgetting which channel is which, or not checking both in post.",
    compareWith: "Gain staging, clipping",
  },
  {
    slug: "room-tone",
    name: "Room Tone", abbr: "TONE", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "30–60 seconds of the location's ambient silence recorded with everyone quiet.",
    communicates: "The bed you lay under edits so cuts don't sound like dead silence.",
    whenToUse: "At every location, after the take, before moving on.",
    howToAchieve: "Keep the exact mic and gain, have everyone freeze, and roll on the quiet room.",
    equipment: "Your recording setup — nothing extra.",
    commonMistake: "Forgetting to grab it and being unable to smooth cuts in post.",
    compareWith: "Wind protection, gain staging",
  },
  {
    slug: "wind-protection",
    name: "Wind Protection", abbr: "WIND", category: "audio", accent: "info", tool: "/tools/audio",
    definition: "Foam, fur (deadcat) or a blimp that blocks wind hitting the mic capsule.",
    communicates: "Outdoor dialogue without the rumbling thumps of wind noise.",
    whenToUse: "Any outdoor or moving-air environment.",
    howToAchieve: "Match protection to conditions: foam for light air, fur or blimp for wind.",
    equipment: "Foam windscreen, fur windshield, blimp with shock mount.",
    commonMistake: "Using a bare capsule outdoors and ruining every take.",
    compareWith: "Boom, room tone",
  },

  // ---------------- EDITING ----------------
  {
    slug: "match-cut",
    name: "Match Cut", abbr: "MATCH", category: "editing", accent: "flare", tool: "/learn",
    definition: "A cut between two shots matched on shape, motion or composition.",
    communicates: "A elegant link across time or space — 'these two things rhyme'.",
    whenToUse: "For stylish transitions and to connect ideas across scenes.",
    howToAchieve: "Frame two different subjects so a graphic or motion element aligns, then cut on it.",
    equipment: "Shot coverage with composition in mind; an editor's eye.",
    commonMistake: "A near-match that just reads as a continuity error.",
    compareWith: "Jump cut, match on action",
  },
  {
    slug: "jump-cut",
    name: "Jump Cut", abbr: "JUMP", category: "editing", accent: "flare", tool: "/learn",
    definition: "Cutting within the same continuous shot, skipping forward in time.",
    communicates: "Compressed time, unease, or fast talking-to-camera energy.",
    whenToUse: "For vlogs, condensing interviews, or deliberately jarring effects.",
    howToAchieve: "Cut out beats from a single take, ideally on a motion or word.",
    equipment: "Single-camera coverage.",
    commonMistake: "Visible jumps in body position that feel accidental rather than deliberate.",
    compareWith: "Match cut, J-cut",
  },
  {
    slug: "j-l-cut",
    name: "J-Cut & L-Cut", abbr: "J/L", category: "editing", accent: "flare", tool: "/learn",
    definition: "Audio leads or trails the picture: a J-cut brings audio in early; an L-cut lets it run over the next shot.",
    communicates: "Smooth, natural transitions that mimic how attention actually shifts.",
    whenToUse: "In almost every dialogue scene to make cuts feel invisible.",
    howToAchieve: "Offset the audio edit point from the video edit point by a few frames.",
    equipment: "Any non-linear editor.",
    commonMistake: "Hard audio-video cuts that feel mechanical and jarring.",
    compareWith: "Jump cut, cross-cutting",
  },
  {
    slug: "cross-cutting",
    name: "Cross-Cutting", abbr: "X-CUT", category: "editing", accent: "flare", tool: "/learn",
    definition: "Cutting between two simultaneous actions to imply they happen at once.",
    communicates: "Tension, parallelism and the feeling of a countdown.",
    whenToUse: "For chases, converging storylines and building suspense.",
    howToAchieve: "Alternate shots of two lines of action, tightening the rhythm as they converge.",
    equipment: "Coverage of both actions; rhythmic editing.",
    commonMistake: "Losing spatial clarity so the viewer can't tell where anyone is.",
    compareWith: "Shot-reverse-shot, parallel action",
  },
  {
    slug: "match-on-action",
    name: "Match on Action", abbr: "MoA", category: "editing", accent: "flare", tool: "/learn",
    definition: "Cutting from one shot to another in the middle of a continuous movement.",
    communicates: "Seamless continuity — the edit is hidden inside the motion.",
    whenToUse: "To join coverage invisibly and keep energy flowing.",
    howToAchieve: "Cut on the peak of a gesture so the motion carries across the cut.",
    equipment: "Overlapping coverage of the action from multiple angles.",
    commonMistake: "Cutting on mismatched speed or direction so the action stutters.",
    compareWith: "Match cut, continuity",
  },
  {
    slug: "180-degree-rule",
    name: "180-Degree Rule", abbr: "180°", category: "editing", accent: "flare", tool: "/learn",
    definition: "Keep the camera on one side of an imaginary line between two subjects so screen direction stays consistent.",
    communicates: "Stable spatial relationships — viewers always know who faces whom.",
    whenToUse: "In every dialogue scene unless you deliberately cross the line for effect.",
    howToAchieve: "Draw the line of action between subjects and keep cameras on one side of it.",
    equipment: "An awareness of the line; coverage from one half of the circle.",
    commonMistake: "Crossing the line and flipping which way characters look at each other.",
    compareWith: "30-degree rule, eyeline match",
  },
  {
    slug: "shot-reverse-shot",
    name: "Shot / Reverse Shot", abbr: "SRS", category: "editing", accent: "flare", tool: "/learn",
    definition: "Alternating between two angles — typically over-the-shoulder views — in a conversation.",
    communicates: "The standard grammar of dialogue — back and forth, face to face.",
    whenToUse: "For virtually all dialogue scenes.",
    howToAchieve: "Cover both sides with matched eyelines, respecting the 180° line, then alternate.",
    equipment: "Two matching over-the-shoulder angles.",
    commonMistake: "Mismatched eyelines so the characters don't appear to look at each other.",
    compareWith: "Over-the-shoulder, 180-degree rule",
  },
  {
    slug: "cutaway",
    name: "Cutaway / Insert", abbr: "CUT", category: "editing", accent: "flare", tool: "/learn",
    definition: "A shot that cuts away from the main action to related detail or reaction.",
    communicates: "Added information, emphasis, or a way to hide an edit in dialogue.",
    whenToUse: "To cover a jump cut, add reaction, or point at a detail.",
    howToAchieve: "Shoot B-roll, reaction shots and inserts during coverage to cut to.",
    equipment: "Extra coverage beyond the master.",
    commonMistake: "Cutting to unrelated B-roll that breaks the scene's flow.",
    compareWith: "Insert shot, reaction shot",
  },
];

export const topics: Topic[] = [...baseTopics, ...departmentTopics];

export function topicsByCategory(categoryId: string): Topic[] {
  return topics.filter((t) => t.category === categoryId);
}

export function findTopic(slug: string): Topic | undefined {
  return topics.find((t) => t.slug === slug);
}

export function categoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function isDepartmentVisible(departments: string[] | undefined, deptId: string): boolean {
  return deptId === "all" || Boolean(departments?.includes("all") || departments?.includes(deptId));
}

export function canAccessTopic(topic: Topic, deptId: string): boolean {
  return isDepartmentVisible(topic.departments ?? categoryById(topic.category)?.departments, deptId);
}

export function getTopicsByDepartment(deptId: string): Topic[] {
  return topics.filter((topic) => canAccessTopic(topic, deptId));
}

export function getCategoriesByDepartment(deptId: string): Category[] {
  return categories.filter((category) =>
    isDepartmentVisible(category.departments, deptId) ||
    topics.some((topic) => topic.category === category.id && isDepartmentVisible(topic.departments, deptId)),
  );
}
