import type { Category, Topic } from "@/lib/content";

export const departmentCategories: (Category & { departments: string[] })[] = [
  // Directing
  {
    id: "directing-craft",
    name: "Directing & Blocking",
    abbr: "DIR",
    blurb: "Scene breakdown, character objectives, blocking, and coverage grammar",
    accent: "info",
    tool: "/tools/directing-blocking",
    departments: ["directing"],
  },
  {
    id: "screen-grammar",
    name: "Screen Direction & Eyelines",
    abbr: "EYE",
    blurb: "180-degree line, eyeline matches, and spatial continuity",
    accent: "info",
    tool: "/tools/directing-180",
    departments: ["directing", "script-continuity", "cinematography"],
  },
  // Lighting and Grip
  {
    id: "lighting-grip-craft",
    name: "Grip & Fixture Staging",
    abbr: "GRP",
    blurb: "Key-to-fill ratios, negative fill, diffusion, and safety rigging",
    accent: "amber",
    tool: "/tools/lighting-studio",
    departments: ["lighting-grip", "cinematography"],
  },
  {
    id: "power-rigging",
    name: "Power & Cable Safety",
    abbr: "PWR",
    blurb: "Amperage loads, voltage drop, cable distribution, and circuit safety",
    accent: "amber",
    tool: "/tools/lighting-power",
    departments: ["lighting-grip", "production"],
  },
  // Sound
  {
    id: "sound-craft",
    name: "Location Sound Rigging",
    abbr: "SND",
    blurb: "Boom placement, wireless lavaliers, wind protection, and wild lines",
    accent: "ok",
    tool: "/tools/sound-rigging",
    departments: ["sound"],
  },
  {
    id: "audio-staging",
    name: "Gain Staging & Sync",
    abbr: "GAIN",
    blurb: "Transmitter trim, receiver output, camera input levels, and timecode",
    accent: "ok",
    tool: "/tools/sound-gain",
    departments: ["sound", "editing-post"],
  },
  // Assistant Directing
  {
    id: "ad-craft",
    name: "AD Scheduling & Set Ops",
    abbr: "SCHD",
    blurb: "Shooting schedules, DOODs, call sheets, and set safety announcements",
    accent: "rec",
    tool: "/tools/ad-schedule",
    departments: ["assistant-directing", "production"],
  },
  // Production
  {
    id: "production-craft",
    name: "Production Management",
    abbr: "PROD",
    blurb: "Budgets, timeline planning, location permits, releases, and insurance",
    accent: "info",
    tool: "/tools/prod-budget",
    departments: ["production", "assistant-directing"],
  },
  // Production Design
  {
    id: "art-craft",
    name: "Production Design & Color",
    abbr: "ART",
    blurb: "Color palettes, mood boards, set dressing, texture, and props breakdown",
    accent: "amber",
    tool: "/tools/art-palette",
    departments: ["production-design", "directing"],
  },
  // Script and Continuity
  {
    id: "continuity-craft",
    name: "Script & Continuity Logging",
    abbr: "CONT",
    blurb: "Take logging, circle takes, dialogue changes, and continuity tracking",
    accent: "info",
    tool: "/tools/script-logger",
    departments: ["script-continuity", "directing", "editing-post"],
  },
  // Editing and Post
  {
    id: "post-craft",
    name: "Editing Grammar & Post Workflow",
    abbr: "POST",
    blurb: "Assembly, J/L cuts, proxy workflow, codecs, and color delivery",
    accent: "flare",
    tool: "/tools/post-storage",
    departments: ["editing-post", "sound", "cinematography"],
  },
];

export const departmentTopics: (Topic & { departments: string[] })[] = [
  // ================= DIRECTING TOPICS =================
  {
    slug: "scene-breakdown",
    name: "Scene Breakdown",
    abbr: "BRK",
    category: "directing-craft",
    accent: "info",
    tool: "/tools/directing-blocking",
    departments: ["directing", "assistant-directing", "script-continuity"],
    definition: "The systematic analysis of a dramatic script scene into functional beats, character objectives, subtext, and physical production requirements.",
    communicates: "Transforms literary text into actionable visual instructions, character motivations, and blocking requirements for the entire crew.",
    whenToUse: "During pre-production for every script scene before scheduling, storyboarding, or blocking rehearsal on set.",
    howToAchieve: "Divide the script page into eighths (1/8ths), highlight character entrances/exits, identify the primary dramatic conflict, and list key props or visual cues.",
    equipment: "Script breakdown sheets, colored highlighters, digital script lining software.",
    commonMistake: "Focusing only on dialogue while ignoring the physical actions, subtextual shifts, and emotional turns that motivate camera placement.",
    compareWith: "Blocking planner, coverage planner, storyboard",
  },
  {
    slug: "character-objectives",
    name: "Character Objectives & Beats",
    abbr: "OBJ",
    category: "directing-craft",
    accent: "info",
    tool: "/tools/directing-blocking",
    departments: ["directing", "script-continuity"],
    definition: "What a character actively wants in a scene (the super-objective and scene goal) and the distinct emotional turns (beats) they take to get it.",
    communicates: "Drives actor performance, determines who has status or power in the frame, and dictates when the camera should push in or cut.",
    whenToUse: "When directing actors in rehearsal and deciding where to place key reaction close-ups and camera movement shifts.",
    howToAchieve: "Define each character's action verb (to intimidate, to seduce, to evade). When a tactic changes or new information lands, mark an emotional beat.",
    equipment: "Director's annotated script, rehearsal floor space.",
    commonMistake: "Giving actors result-oriented direction ('be sad', 'look angry') instead of actionable objective verbs ('try to force him to confess').",
    compareWith: "Performance notes, shot motivation",
  },
  {
    slug: "blocking-planner",
    name: "Staging & Blocking",
    abbr: "BLK",
    category: "directing-craft",
    accent: "info",
    tool: "/tools/directing-blocking",
    departments: ["directing", "cinematography", "assistant-directing"],
    definition: "The precise choreography of actor movement and camera positioning within the physical set or location space across a scene.",
    communicates: "Establishes spatial relationships, power dynamics, character intimacy or isolation, and visual pacing without relying purely on editing cuts.",
    whenToUse: "At the start of every new scene setup before lighting is finalized ('Block, Light, Rehearse, Shoot').",
    howToAchieve: "Walk through the scene with actors on set, find natural motivations for movement (pouring a drink, crossing to a window), and place camera marks.",
    equipment: "Actor T-marks (sausages/tape), viewfinder or director's finder, top-down floor plan.",
    commonMistake: "Locking the camera position first and forcing actors to stand rigidly in static marks that feel theatrical and unnatural.",
    compareWith: "Coverage planner, screen-direction guide",
  },
  {
    slug: "coverage-planner",
    name: "Shot Coverage Grammar",
    abbr: "COV",
    category: "directing-craft",
    accent: "info",
    tool: "/tools/directing-blocking",
    departments: ["directing", "cinematography", "editing-post"],
    definition: "The planned collection of camera setups (masters, medium two-shots, over-the-shoulders, close-ups, and inserts) required to edit a scene cohesively.",
    communicates: "Provides the editor with the necessary angles, pacing options, and performance protection to construct the scene's emotional rhythm.",
    whenToUse: "During prep when building the director's shot list and on set when deciding which setups are mandatory vs optional.",
    howToAchieve: "Start with an establishing master shot for geography, move into medium over-the-shoulder dialogue coverage, and end on tight emotional singles.",
    equipment: "Shot list sheet, storyboards, 2-camera or single-camera package.",
    commonMistake: "Over-shooting redundant medium setups while forgetting critical insert shots (a text message, a turning doorknob) needed for continuity.",
    compareWith: "Shot list, 180-degree rule",
  },
  {
    slug: "180-degree-rule-dir",
    name: "180-Degree Line & Screen Direction",
    abbr: "180°",
    category: "screen-grammar",
    accent: "info",
    tool: "/tools/directing-180",
    departments: ["directing", "cinematography", "script-continuity", "editing-post"],
    definition: "An imaginary axis drawn between two interacting characters that dictates all camera placements must remain on one 180-degree side of the line.",
    communicates: "Maintains spatial clarity so that Character A always looks screen-right and Character B always looks screen-left across alternating cuts.",
    whenToUse: "In every multi-angle dialogue scene, action sequence, or character movement sequence to prevent audience disorientation.",
    howToAchieve: "Establish the line of action between actor eyelines. Place all cameras (Master, OTS A, OTS B, CU A, CU B) within the same 180° semicircle.",
    equipment: "Top-down stage diagram, script supervisor continuity log.",
    commonMistake: "Accidentally crossing the line when moving the camera for a close-up, causing both characters to look in the exact same screen direction when edited.",
    compareWith: "Eyeline match, blocking planner",
  },
  {
    slug: "eyeline-guide",
    name: "Eyeline Match & Vertical Pacing",
    abbr: "EYE",
    category: "screen-grammar",
    accent: "info",
    tool: "/tools/directing-180",
    departments: ["directing", "cinematography", "script-continuity"],
    definition: "Aligning the actor's gaze direction and lens height across separate camera setups so looking angles connect seamlessly in the edit.",
    communicates: "Creates the subconscious illusion that two characters filmed hours or days apart are looking directly into each other's eyes.",
    whenToUse: "When shooting over-the-shoulder (OTS) reverses and clean close-up singles in dialogue coverage.",
    howToAchieve: "Match lens height to the eyeline of the character being addressed. If Actor A is seated looking up at standing Actor B, Actor A's close-up must look slightly above lens level.",
    equipment: "Matte box eyeline mark, off-camera eye-target stand or actor stand-in.",
    commonMistake: "Letting an actor look too close to or directly into the lens during narrative drama, breaking the 4th wall and destroying audience immersion.",
    compareWith: "180-degree rule, camera angles",
  },

  // ================= LIGHTING AND GRIP TOPICS =================
  {
    slug: "key-to-fill-ratios",
    name: "Key-to-Fill Lighting Ratios",
    abbr: "RATIO",
    category: "lighting-grip-craft",
    accent: "amber",
    tool: "/tools/lighting-studio",
    departments: ["lighting-grip", "cinematography"],
    definition: "The mathematical brightness difference between the dominant Key light and the shadow-softening Fill light on a subject's face (e.g., 2:1, 4:1, 8:1).",
    communicates: "Dictates visual mood: low ratios (2:1) read bright, optimistic, and commercial (High-Key); high ratios (8:1+) read dramatic, moody, and noir (Low-Key).",
    whenToUse: "When setting exposure and mood during lighting block for narrative drama, corporate interviews, or commercial beauty setups.",
    howToAchieve: "Measure key side footcandles or f-stop with an incident meter. To achieve a 4:1 ratio, set the fill light exactly 2 stops darker than the key light.",
    equipment: "Incident light meter, LED/HMI key fixture, fill bounce or scrim, dimmers.",
    commonMistake: "Over-filling the shadow side until facial sculpting is destroyed, resulting in a flat, two-dimensional broadcast look.",
    compareWith: "Negative fill, three-point lighting, bounce and diffusion",
  },
  {
    slug: "negative-fill-grip",
    name: "Negative Fill & Flag Rigging",
    abbr: "NEG",
    category: "lighting-grip-craft",
    accent: "amber",
    tool: "/tools/lighting-studio",
    departments: ["lighting-grip", "cinematography"],
    definition: "Using solid black fabric (duvetyne, solid flags, or black foamcore) to absorb ambient room bounce and deepen shadows on the subject.",
    communicates: "Sculpts facial features, increases contrast, and adds dramatic depth even in small, white-walled location rooms.",
    whenToUse: "Whenever ambient room reflections are washing out the shadow side of your talent's face.",
    howToAchieve: "Position a 4x4 solid flag or 8x8 black floppy on a C-stand just out of camera frame on the side opposite the key light.",
    equipment: "C-stands, grip heads, sandbags, 4x4 solid flags, 8x8 floppies, duvetyne rolls.",
    commonMistake: "Forgetting to sandbag high C-stand rigging when placing large black floppies near talent or moving crew.",
    compareWith: "Key-to-fill ratios, bounce and diffusion",
  },
  {
    slug: "bounce-and-diffusion",
    name: "Bounce, Scrims & Diffusion Fabrics",
    abbr: "DIFF",
    category: "lighting-grip-craft",
    accent: "amber",
    tool: "/tools/lighting-studio",
    departments: ["lighting-grip", "cinematography"],
    definition: "Modifying hard light sources by transmitting them through translucent textiles (silk, grid cloth, frost) or reflecting them off surfaces (muslin, ultrabounce, beadboard).",
    communicates: "Increases the physical size of the light source, creating gentle, wrapping highlight transitions and soft, flattering shadows.",
    whenToUse: "When lighting talent faces in close-ups, interviews, and beauty commercials, or when taming harsh direct sunlight outdoors.",
    howToAchieve: "Rig a 4x4 or 6x6 frame of Silent Frost or Grid Cloth between your hard light fixture and the talent. The closer the diffusion is to the talent, the softer the wrap.",
    equipment: "Butterfly/overhead frames, grip heads, rags (Full Grid, 1/2 Frost, Silk), Unbleached Muslin, Beadboard.",
    commonMistake: "Placing the diffusion frame right against the lamp face; the source only gets softer if the diffusion fabric itself is physically large and closer to talent.",
    compareWith: "Hard vs soft light, negative fill",
  },
  {
    slug: "power-and-cable-planning",
    name: "Amperage Loads & Cable Distribution",
    abbr: "AMP",
    category: "power-rigging",
    accent: "amber",
    tool: "/tools/lighting-power",
    departments: ["lighting-grip", "production"],
    definition: "Calculating total electrical wattage requirements against available circuit amperage (Watts = Volts × Amps) to prevent tripped breakers or electrical fires.",
    communicates: "Ensures set safety, unbroken shooting momentum, and proper generator or distribution box sizing for lighting packages.",
    whenToUse: "During technical location scouts and during lighting prep before plugging heavy HMI, Tungsten, or high-output LED fixtures into wall outlets.",
    howToAchieve: "Use the field paper math rule: Amps = Watts ÷ 100 (in 120V US countries for a 20% safety margin). A 15A household circuit can safely carry 1500W total.",
    equipment: "Multimeter, AC circuit tester, 12/3 stingers (extension cords), distribution lunchboxes, cable stingers, cable crossovers/yellow jackets.",
    commonMistake: "Plugging multiple high-output lights into different wall outlets in the exact same room without realizing all outlets share a single 15A household breaker.",
    compareWith: "Grip equipment guide, set safety checklist",
  },

  // ================= SOUND TOPICS =================
  {
    slug: "boom-placement-diagrams",
    name: "Boom Microphone Staging & Angles",
    abbr: "BOOM",
    category: "sound-craft",
    accent: "ok",
    tool: "/tools/sound-rigging",
    departments: ["sound"],
    definition: "Positioning a directional shotgun or hypercardioid microphone on a boom pole just out of camera frame above or below speaking talent.",
    communicates: "Captures natural, full-bodied vocal dialogue with accurate acoustic room perspective and physical depth.",
    whenToUse: "The primary choice for narrative dialogue on quiet interior sets or controlled exterior locations.",
    howToAchieve: "Hold the boom pole overhead just above the camera frame line, point the mic capsule down at a 45-degree angle toward the actor's mouth/sternum.",
    equipment: "Carbon fiber boom pole, shock mount, shotgun mic (Sennheiser MKH416 / Schoeps CMIT5), internal cabled pole.",
    commonMistake: "Aiming the mic straight down at the top of the actor's head instead of angling toward the chest/mouth, causing muffled high frequencies and throat resonance.",
    compareWith: "Lavalier placement, room tone",
  },
  {
    slug: "lavalier-placement-sound",
    name: "Lavalier Hitching & Clothing Rustle",
    abbr: "LAV",
    category: "sound-craft",
    accent: "ok",
    tool: "/tools/sound-rigging",
    departments: ["sound"],
    definition: "Concealing miniature electret condenser microphones inside actor wardrobe or on the chest using specialized mounts and adhesives.",
    communicates: "Delivers intimate, isolated dialogue presence with maximum rejection of ambient location background noise.",
    whenToUse: "In wide master shots where boom mics cannot reach, during documentary interviews, or in noisy, reverberant location spaces.",
    howToAchieve: "Mount the capsule on the center chest over the sternum using moleskin, Rycote Overcovers, or vampire clips. Create a broadcast broadcast loop in the wire to isolate tension.",
    equipment: "Miniature lavalier mics (Sanken COS-11D / DPA 4060), moleskin, medical tape, Ursa MiniMounts, concealer moleskin.",
    commonMistake: "Taping the microphone directly against rigid synthetic fabrics (polyester/silk) that scrape across the capsule whenever the actor breathes or turns.",
    compareWith: "Boom placement, gain-staging simulator",
  },
  {
    slug: "gain-staging-sound",
    name: "Audio Gain Staging & Transmitter Trim",
    abbr: "GAIN",
    category: "audio-staging",
    accent: "ok",
    tool: "/tools/sound-gain",
    departments: ["sound", "editing-post", "cinematography"],
    definition: "Calibrating audio signal voltage levels sequentially from microphone capsule to transmitter trim, receiver output, and camera/recorder preamp input.",
    communicates: "Maximizes signal-to-noise ratio, ensuring crystal-clear dialogue recordings free of analog tape hiss or digital clipping distortion.",
    whenToUse: "During morning sound prep and before rolling on every new actor setup or loudness dynamic change.",
    howToAchieve: "Set transmitter sensitivity so loud dialogue peaks around -12 dBFS on transmitter meter. Set receiver output to line-level or mic-level to match camera preamp.",
    equipment: "Wireless transmitter/receiver packs (Lectrosonics / Wisycom / Sound Devices), multi-track field recorder (Sound Devices 833 / Zoom F8n).",
    commonMistake: "Setting transmitter trim too low (inducing heavy wireless hiss) while cranking camera input preamps to maximum to compensate.",
    compareWith: "Safety tracks, audio troubleshooting",
  },
  {
    slug: "room-tone-wild-lines",
    name: "Location Room Tone & Wild Lines",
    abbr: "TONE",
    category: "sound-craft",
    accent: "ok",
    tool: "/tools/sound-rigging",
    departments: ["sound", "editing-post", "assistant-directing"],
    definition: "Recording 60 seconds of location ambient silence (room tone) and off-camera audio-only dialogue takes (wild lines) immediately following a visual take.",
    communicates: "Provides dialogue editors with clean acoustic background beds to patch edit transitions and replace muffled on-camera dialogue without expensive ADR studio sessions.",
    whenToUse: "Mandatory at the end of every scene location setup before crew breakdown or company move.",
    howToAchieve: "Have the 1st AD call 'Quiet on set for 60 seconds of room tone.' Keep crew frozen, lights burning, and microphones in exact shooting position.",
    equipment: "Primary location sound package, boom and lav channels rolling simultaneously.",
    commonMistake: "Allowing crew members to whisper, pack gear, or shuffle feet during room tone recording, rendering the ambient bed useless for post-production patching.",
    compareWith: "Sound reports, boom placement",
  },

  // ================= ASSISTANT DIRECTING TOPICS =================
  {
    slug: "shooting-schedule-ad",
    name: "Shooting Schedule & Page-Count Estimating",
    abbr: "SCHD",
    category: "ad-craft",
    accent: "rec",
    tool: "/tools/ad-schedule",
    departments: ["assistant-directing", "production", "directing"],
    definition: "Organizing script scenes into an efficient chronological shooting order based on location availability, actor turnarounds, lighting resets, and page eighths.",
    communicates: "Defines the daily operational speed, required company hours, and logistical feasibility of completing the production on budget and on time.",
    whenToUse: "During pre-production after script breakdown and dynamically updated on set as weather, company moves, or scene complexities shift.",
    howToAchieve: "Group scenes by Location and Day/Night. In narrative drama, budget 3 to 5 pages per 10-hour shooting day; for complex setups or stunts, budget 1 to 2 pages.",
    equipment: "Scheduling software (Movie Magic / StudioBinder), stripboards, production calendar.",
    commonMistake: "Scheduling complex night exteriors, company moves, or company company company moves on Day 1 when the crew is still establishing communication rhythm.",
    compareWith: "Call-sheet checklist, daily production report",
  },
  {
    slug: "call-sheet-prep",
    name: "Daily Call Sheet Generation & Safety Notes",
    abbr: "CALL",
    category: "ad-craft",
    accent: "rec",
    tool: "/tools/ad-schedule",
    departments: ["assistant-directing", "production", "all"],
    definition: "The formal daily operational document issued to all cast and crew detailing call times, location maps, nearest hospital, scene order, and weather forecasts.",
    communicates: "Serves as the legally binding daily itinerary and communication hub that synchronizes all 9 film departments for the upcoming shoot day.",
    whenToUse: "Published and distributed by the 2nd AD at least 12 hours prior to crew call time.",
    howToAchieve: "Verify location addresses, confirm actor pickup times with transport, list nearest emergency room address with phone number, and attach daily safety briefing topics.",
    equipment: "Call sheet template, production distribution email / messaging list.",
    commonMistake: "Issuing call sheets without verifying nearest hospital emergency room details or failing to clearly highlight staggered individual department call times.",
    compareWith: "Shooting schedule, day-out-of-days",
  },

  // ================= PRODUCTION TOPICS =================
  {
    slug: "budget-categories-prod",
    name: "Above/Below-the-Line Budget Breakdown",
    abbr: "BUDG",
    category: "production-craft",
    accent: "info",
    tool: "/tools/prod-budget",
    departments: ["production", "assistant-directing"],
    definition: "Dividing production expenditure into Above-the-Line (creative talent: Director, Producers, Cast, Writer) and Below-the-Line (physical production: Crew, Gear, Locations, Post).",
    communicates: "Establishes financial governance, insurance bonding valuation, and department equipment allocation caps across the production lifecycle.",
    whenToUse: "During initial project financing, pre-production planning, and weekly cost-to-complete tracking.",
    howToAchieve: "Allocate ~30% of total budget to Above-the-Line, ~55% to Below-the-Line physical production, ~15% to Post-production and mandatory 10% contingency reserves.",
    equipment: "Production budgeting spreadsheets, accounting software (Movie Magic Budgeting).",
    commonMistake: "Omitting mandatory payroll fringe taxes, workers' compensation insurance, or location cleaning/restoration fees from Below-the-Line calculations.",
    compareWith: "Production timeline, insurance checklist",
  },
  {
    slug: "release-forms-permits",
    name: "Location Permits & Talent Release Forms",
    abbr: "LEGAL",
    category: "production-craft",
    accent: "info",
    tool: "/tools/prod-budget",
    departments: ["production", "all"],
    definition: "Executing legally binding licensing agreements granting the production company right of entry to properties and commercial rights to actor/background likenesses.",
    communicates: "Proteects the film from copyright infringement lawsuits, location eviction by municipal authorities, and distribution rejection by streaming platforms.",
    whenToUse: "Secured during location scouting and signed by every cast member, extra, or location owner prior to rolling camera.",
    howToAchieve: "Keep physical clipboard folders of standard Location Agreements, Actor Releases, and Crowd Notice signs. Have PAs collect signatures before talent enters hair/makeup.",
    equipment: "Printed release binders, digital e-signature tablets, municipal filming permit certificates.",
    commonMistake: "Filming recognizable private brand trademarks, artwork, or background passersby on commercial streets without posted crowd notice signs or signed releases.",
    compareWith: "Insurance checklist, client approvals",
  },

  // ================= PRODUCTION DESIGN TOPICS =================
  {
    slug: "color-palette-builder-art",
    name: "5-Color Scene Palette & Mood Staging",
    abbr: "PAL",
    category: "art-craft",
    accent: "amber",
    tool: "/tools/art-palette",
    departments: ["production-design", "directing", "cinematography"],
    definition: "Curating a structured 5-color harmonic spectrum (Dominant, Secondary, Accent, Neutral, Contrast) that dictates set walls, wardrobe, and prop finishes for a scene.",
    communicates: "Subconsciously signals character psychology, temporal eras, narrative themes, and visual contrast against the cinematographer's lighting gel choices.",
    whenToUse: "Developed in pre-production visual treatments and referenced during set dressing, costume fittings, and color grading.",
    howToAchieve: "Select a dominant wall/environment tone (60%), support with secondary furniture/drapery tones (30%), and reserve a vibrant contrast accent color (10%) for key hero props.",
    equipment: "Color swatches (Pantone/RAL), fabric samples, digital mood board software.",
    commonMistake: "Designing set dressing colors in complete isolation without checking the cinematographer's intended lighting gel color temperature (e.g., sodium vapor vs cool LED).",
    compareWith: "Props breakdown, material and texture boards",
  },
  {
    slug: "props-continuity-art",
    name: "Hero Props Breakdown & Set Continuity",
    abbr: "PROP",
    category: "art-craft",
    accent: "amber",
    tool: "/tools/art-palette",
    departments: ["production-design", "script-continuity", "directing"],
    definition: "Cataloging and managing all movable items handled by actors (Hero props), background dressing (Set dec), and their precise physical condition across takes.",
    communicates: "Ensures narrative authenticity and prevents jarring visual continuity errors when props are consumed, destroyed, or moved between cuts.",
    whenToUse: "During script breakdown to identify required multiples (e.g., 6 identical letters for tearing) and maintained on set between every camera take.",
    howToAchieve: "Label prop tables by character and scene. Always acquire 'multiples' (3x to 5x duplicates) for food, breakaway items, or blood-stained garments.",
    equipment: "Prop table organization crates, Polaroid/smartphone reference camera, labeling tape.",
    commonMistake: "Having only a single unique hero prop on set for a scene where the script requires the actor to smash, throw, or stain the item during close-up coverage.",
    compareWith: "Set dressing checklist, wardrobe references",
  },

  // ================= SCRIPT AND CONTINUITY TOPICS =================
  {
    slug: "take-logging-slate",
    name: "Take Logging & Circle Take Marking",
    abbr: "LOG",
    category: "continuity-craft",
    accent: "info",
    tool: "/tools/script-logger",
    departments: ["script-continuity", "directing", "cinematography", "editing-post"],
    definition: "The rigorous documentation of every recorded camera/sound slate, take number, runtime duration, technical faults, and director's preferred 'Circle Takes'.",
    communicates: "Provides the assistant editor with the authoritative roadmap to immediately organize footage, cull false takes, and assemble the director's preferred performance.",
    whenToUse: "Recorded continuously on set during every camera roll from initial slate clap to director's cut.",
    howToAchieve: "Listen to 2nd AC slate announcement, start stopwatch on timecode sync, log dialogue flubs or boom dips, and draw a physical circle around the take number when the director approves.",
    equipment: "Script supervisor take sheets, digital continuity iPad (ScriptE), stopwatch, physical binder.",
    commonMistake: "Failing to confirm with the director immediately after a take whether it was a printed 'Circle Take', leaving post-production guessing which take to assemble.",
    compareWith: "Scene notes, editor notes",
  },
  {
    slug: "continuity-photographs",
    name: "Continuity Line Sheets & Reference Photos",
    abbr: "LINE",
    category: "continuity-craft",
    accent: "info",
    tool: "/tools/script-logger",
    departments: ["script-continuity", "directing", "production-design", "editing-post"],
    definition: "Taking high-resolution timestamped photos of actor wardrobe, prop placement, hair/makeup state, and drawing vertical lines down script pages showing exact camera coverage.",
    communicates: "Prevents embarrassing continuity errors across multi-day shoots and proves to the director and editor exactly which dialogue lines were captured in close-up vs master.",
    whenToUse: "At the end of every approved setup before actors leave set or change wardrobe.",
    howToAchieve: "Photograph talent from front, side, and back. Draw a straight vertical line down the script text covered by Slate 10A, using a wavy line where talent was off-camera.",
    equipment: "iPad continuity software, smartphone camera, lined script binder.",
    commonMistake: "Relying on memory or verbal confirmation from wardrobe/prop assistants instead of checking physical photographic timestamps from previous shooting days.",
    compareWith: "Take logging, eyeline tracking",
  },

  // ================= EDITING AND POST TOPICS =================
  {
    slug: "proxy-workflow-codecs",
    name: "Proxy Workflow & Delivery Codecs",
    abbr: "PRXY",
    category: "post-craft",
    accent: "flare",
    tool: "/tools/post-storage",
    departments: ["editing-post", "cinematography", "production"],
    definition: "Transcoding heavy, high-resolution camera RAW / All-Intra files (4K/6K/8K) into lightweight editing files (ProRes 422 Proxy / DNxHR LB) for fluid offline editing before relinking for final color.",
    communicates: "Eliminates computer playback stutter, enables rapid multi-cam timeline scrubbing on standard laptops, and streamlines remote collaborative editing.",
    whenToUse: "Initiated immediately by the Assistant Editor during data wrangling before creative cutting begins.",
    howToAchieve: "Ingest original camera RAW cards, generate 1080p ProRes Proxy files matching exact source timecode and filename, edit offline, then toggle back to RAW for DaVinci Resolve grading.",
    equipment: "NLE software (Premiere Pro / DaVinci Resolve / Final Cut), high-speed RAID storage, DIT checksum software (Silverstack / ShotPut Pro).",
    commonMistake: "Renaming proxy files or stripping embedded timecode during transcode, making it mathematically impossible to relink timeline edits back to original camera RAW files.",
    compareWith: "Codec guide, delivery formats",
  },
  {
    slug: "jl-cuts-pacing",
    name: "J-Cuts, L-Cuts & Audio Transition Pacing",
    abbr: "J/L",
    category: "post-craft",
    accent: "flare",
    tool: "/tools/post-storage",
    departments: ["editing-post", "directing", "sound"],
    definition: "Split edits where audio and video transition points are offset: a J-cut introduces the next scene's audio before the video cut; an L-cut extends current audio over the next video shot.",
    communicates: "Mimics natural human visual perception and listening psychology, making edit points invisible and creating conversational fluidity in dialogue scenes.",
    whenToUse: "Applied in over 90% of narrative dialogue cuts and documentary interview transitions to eliminate mechanical, robotic cuts.",
    howToAchieve: "Unlink audio and video clips on the timeline. Advance the incoming speaking character's audio track 12 to 24 frames before cutting to their visual reaction close-up.",
    equipment: "Non-linear editing timeline (NLE), studio monitoring monitors or headphones.",
    commonMistake: "Cutting audio and video simultaneously on every single speaker change (a 'dragnet cut' or 'ping-pong cut'), causing visual fatigue and unnatural pacing.",
    compareWith: "Match cuts, continuity editing, pacing guide",
  },
];
